name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # 3. Instalar e configurar o pnpm
      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      # 4. Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # 5. Construir o projeto
      - name: Build project
        run: pnpm build

      # 6. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
