name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Substitua "main" pelo nome do seu branch principal, se necessário.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      # 4. Construir o projeto
      - name: Build project
        run: pnpm build

      # 5. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
