name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js e cache de dependências
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0

      # 3. Instalar e ativar o pnpm
      - name: Install and Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 4. Verificar se o pnpm está disponível
      - name: Check pnpm version
        run: pnpm --version

      # 5. Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # 6. Construir o projeto
      - name: Build project
        run: pnpm run build

      # 7. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./dist
